config/routes.rb
Rails.application.routes.draw do
  get 'home/front'
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
      
  resources :users do
    resources :todo_lists do
      resources :todo_items do
        member do
          patch :complete
          patch :deadline
          get :deadline
          put :move_up
          put :move_down
        end
      end
    end
  end

  resources :todo_lists do
    resources :todo_items do
    end
  end

  root :to => "home#front"
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  acts_as_list scope: :todo_list

  validates :content, presence: true
  validates :content, length: {maximum: 250}
  
  def completed?
  	!completed_at.blank?
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	before_action :set_todo_list
	before_action :set_todo_item, except: [:create, :new]

	def new
		@todo_item = @todo_list.todo_items.new
	end

	def create
		@todo_item = @todo_list.todo_items.create(todo_item_params)
		if @todo_item
			respond_to do |format|
	        format.js
	        format.html { redirect_to action: 'index', notice: 'Item was created.' }
	    end
	  else
     flash[:danger] = 'Item cannot be empty'
    end
	end

	def move_up
  	if @todo_item.move_higher
  		respond_to do |format|
        format.js
        format.html { redirect_to action: 'index' }
    	end
		end
	end

	def move_down
  	if @todo_item.move_lower
  	respond_to do |format|
        format.js
        format.html { redirect_to action: 'index' }
    	end
		end
	end

	def destroy
		if @todo_item.destroy
			respond_to do |format|
        format.js
        format.html { redirect_to action: 'index', notice: 'Item was deleted.' }
    	end
		end
	end

	def edit
  end

  def update
    if @todo_item.update(todo_item_params)
    	if @todo_item[:deadline] != nil
	    	if @todo_item[:deadline] < DateTime.now
					@todo_item.update_attribute(:completed_at, DateTime.now)
				else
					@todo_item.update_attribute(:completed_at, nil)
				end
	    end
	      respond_to do |format|
	        format.js
	        format.html { redirect_to action: 'index', notice: 'Item was updated.' }
	    	end
    else
     flash[:danger] = 'Item cannot be empty'
    end
  end

	def complete
		if @todo_item.completed?
			@todo_item.update_attribute(:completed_at, nil)
			@todo_item.update_attribute(:deadline, nil)
		else
			@todo_item.update_attribute(:completed_at, DateTime.now)
		end
		respond_to do |format|
        format.js
        format.html { redirect_to action: 'index', notice: 'Item was updated.' }
    end
	end

	private

	def set_todo_list
		@todo_list = TodoList.find(params[:todo_list_id])
	end

	def set_todo_item
		@todo_item = @todo_list.todo_items.find(params[:id])
	end

	def todo_item_params
		params.require(:todo_item).permit(:deadline, :content)
	end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_button.html.erb
<div class="trash">
	<%= link_to user_todo_list_todo_item_path(current_user, todo_item[:todo_list_id], todo_item.id), method: :delete, remote: true, class: "delete" do %>
		<i class="far fa-trash-alt fa-sm"></i>
	<% end %> 
	<%= link_to edit_user_todo_list_todo_item_path(current_user, todo_item[:todo_list_id], todo_item.id), remote: true do %>
		<i class="fas fa-pencil-alt fa-sm"></i>
	<% end %>
	<%= link_to move_down_user_todo_list_todo_item_path(current_user, todo_item[:todo_list_id], todo_item.id), method: :put, remote: true do %>
		<i class="fas fa-chevron-up fa-sm"></i>
	<% end %>
	<%= link_to move_up_user_todo_list_todo_item_path(current_user, todo_item[:todo_list_id], todo_item.id), method: :put, remote: true do %>
		<i class="fas fa-chevron-down fa-sm"></i>
	<% end %>
</div>

app/views/todo_items/_check.html.erb
<%= form_for (@todo_item) do |f| %>
	<%= f.check_box :complete, {multiple: true}, 1, nil %>
<% end %>

app/views/todo_items/_edit.html.erb
<div class="row clearfix">
  <div class='icon'>
  	<i class="far fa-calendar-alt fa-2x"></i>
  </div>
  <div class="todo_list_title">
  	<p>Edit Todo Item</p>
	</div>
</div> 
<div class="index_row clearfix" style="padding: 0 2em" >
	<%= form_with model: ([@todo_list, @todo_item]), remote: true do |f| %>
		<div class="field">
			<%= f.text_area :content, placeholder: "Edit Todoss", style: "margin: 0;", required: true %>
		</div>
		<%= f.text_field :deadline ,placeholder: "Click to choose deadline", start_year: DateTime.now.year, style: "width: 72%;" %>
		<%= f.submit %>
	<% end %>
</div>
    


app/views/todo_items/_form.html.erb
<%=  form_with model:([@todo_list, @todo_list.todo_items.build]), remote: true do |f| %>
	<i class="fa fa-plus fa-lg"></i>
	<%= f.text_field :content, placeholder: "Start typing here to create a task...", class: "my_id", required: true %>
	<%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div id="item_<%= todo_item.id %>">
	<div class="row clearfix">
		<% if todo_item[:id]!=nil %>
			<% if todo_item.completed? %>
				<div class="complete">
					<%= link_to complete_user_todo_list_todo_item_path(current_user, todo_item[:todo_list_id], todo_item.id), method: :patch, remote: true, class: "checkbox" do %>
						<input type="checkbox" checked="true" value="" style="zoom:1.5; vertical-align:middle;">
					<% end %>
				</div>
				<div class="todo_item">
					<p><strike style="opacity: 0.4;"><%= todo_item.content %></strike></p>
				</div>
				<%= render partial: 'todo_items/button', locals: {todo_item: todo_item, current_user: current_user} %>
			<% else %>
				<div class="complete">
					<%= link_to complete_user_todo_list_todo_item_path(current_user, todo_item[:todo_list_id], todo_item.id), method: :patch, remote: true, class: "checkbox" do %>
						<input type="checkbox" value="" style="zoom:1.5; vertical-align:middle;">
					<% end %>				
				</div>
				<div class="todo_item">
					<p><%= todo_item.content %></p>
				</div>
				<%= render partial: 'todo_items/button', locals: {todo_item: todo_item, current_user: current_user} %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/todo_items/complete.js.erb
$('#list_<%= @todo_list[:id] %> .items_list').html("<%= j render @todo_list.todo_items.reverse %>");

app/views/todo_items/create.js.erb
$('#list_<%= @todo_list[:id] %> .items_list').show();
$('#list_<%= @todo_list[:id] %> .items_list').prepend("<%= j render @todo_item %>");
$(".my_id").val("");
$('#list_<%= @todo_list[:id] %> #item_').remove();

app/views/todo_items/deadline.html.erb
<%= form_with model: ([@todo_list, @todo_item]) do |f| %>
  <%= f.date_select :deadline, start_year: Time.now.year, default: 3.days.from_now  %>
  <%= f.submit %>
<% end %>

app/views/todo_items/destroy.js.erb
$('.delete').bind('ajax:success', function() {
	$(this).closest('#item_<%= @todo_item.id %>').fadeOut();
});

app/views/todo_items/edit.js.erb
$('#list_<%= @todo_list[:id] %> .row').hide();
$('#list_<%= @todo_list[:id] %>').append("<%= j render 'edit' %>")
$(function() {
  $('#todo_item_deadline').datepicker({
  dateFormat: "yy-mm-dd",
});
});
$('#list_<%= @todo_list[:id] %> .todo_items_wrapper').hide().parent();
$('#list_<%= @todo_list[:id] %>')[0].scrollIntoView({
  behavior: 'auto',
  block: 'center',
  inline: 'center'
});

app/views/todo_items/move_down.js.erb
$('#list_<%= @todo_list[:id] %> .items_list').html("<%= j render @todo_list.todo_items.reverse %>");

app/views/todo_items/move_up.js.erb
$('#list_<%= @todo_list[:id] %> .items_list').html("<%= j render @todo_list.todo_items.reverse %>");

app/views/todo_items/update.js.erb
$('#list_<%= @todo_list[:id] %> form').last().remove();
$('#list_<%= @todo_list[:id] %> .row').last().remove();
$('#list_<%= @todo_list[:id] %> .index_row').last().remove();
$('#list_<%= @todo_list[:id] %> .row').show().parent();
$('#list_<%= @todo_list[:id] %> .todo_items_wrapper').show().parent();
$('#list_<%= @todo_list[:id] %> #item_<%= @todo_item.id %>').replaceWith("<%= j render @todo_item %>");