config/routes.rb
Rails.application.routes.draw do
  get 'home/front'
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
      
  resources :users do
    resources :todo_lists do
      resources :todo_items do
        member do
          patch :complete
          patch :deadline
          get :deadline
          put :move_up
          put :move_down
        end
      end
    end
  end

  resources :todo_lists do
    resources :todo_items do
    end
  end

  root :to => "home#front"
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
	has_many :todo_items, :dependent => :destroy
	has_many :todo_items, -> { order(position: :asc) }
	
	belongs_to :user

	validates :title, presence: true
	validates :title, length: {maximum: 70}
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [ :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_user

  def index
    @user = User.find(params[:user_id])
    @todo_lists = @user.todo_lists
  end

  def show
    @user = User.find(params[:user_id])
    @todo_list = @user.todo_lists.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @todo_list = @user.todo_lists.new
  end

  def edit
    @user = User.find(params[:user_id])
    @todo_list = @user.todo_lists.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @todo_list = @user.todo_lists.find(params[:id])

    if @todo_list.update(todo_list_params)
      respond_to do |format|
        format.js
        format.html { redirect_to action: 'index', notice: 'List was updated.' }
      end
    else
      flash[:danger] = 'List cannot be empty'
    end
  end

  def create
    @user = User.find(params[:user_id])
    @todo_list = @user.todo_lists.create(todo_list_params)

    if @todo_list.save
      respond_to do |format|
        format.js
        format.html { redirect_to action: 'index', notice: 'List was successfully created.' }
      end
    else
      flash[:danger] = 'List cannot be empty'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @todo_list = @user.todo_lists.find(params[:id])

    if @todo_list.destroy
      respond_to do |format|
        format.js
        format.html { redirect_to action: 'index', notice: 'List was deleted.' }
      end
    end
  end

  private

    def check_user
      if current_user != User.find(params[:user_id])
        redirect_to root_path
      end
    end

    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def todo_list_params
      params.require(:todo_list).permit(:title)
    end
  
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_edit.html.erb
<div class="row clearfix">
  <div class='icon'>
    <i class="far fa-calendar-alt fa-2x"></i>
  </div>
  <div class="todo_list_title">
    <p>Edit Todo List</p>
  </div>
</div> 
<%= render 'form' %>

app/views/todo_lists/_form.html.erb
<div class="index_row clearfix" style="padding: 0 2em" >
	<%= form_with model: ([@user, @todo_list]), remote: true do |form| %>
	  <div class="field">	
	    <%= form.text_area :title, class: "h-25", placeholder: "Start typing here to create a project...", required: true %>
	  </div>
	  <div class="actions">
	    <%= form.submit %>
	  </div>
	<% end %>
</div>

app/views/todo_lists/_new.html.erb
<div class="container">
	<div class="index_row clearfix">
		<div class="row clearfix">
      <div class='icon'>
        <i class="far fa-calendar-alt fa-2x"></i>
      </div>
      <div class="todo_list_title">
        <p>Create Todo List</p>
      </div>
    </div>
		<%= render 'form' %>
	</div>
</div>
<p class="footer">

app/views/todo_lists/_todo_list.html.erb
<div class="container">
  <% @todo_list = todo_list %>
  <div class="index_row clearfix" >
    <div id="list_<%= todo_list[:id] %>">
      <div class="row clearfix">
        <div class='icon'>
          <%= link_to destroy_user_session_path, method: :delete, data: { confirm: 'Do you want exit?' } do %>
            <i class="far fa-calendar-alt fa-2x"></i>
          <% end %>
        </div>
        <div class="todo_list_title">
          <p><%= todo_list.title %></p>
        </div>
        <div class="top_links">
          <%= link_to edit_user_todo_list_path(@user, todo_list), remote: true do %> 
            <i class="fas fa-pencil-alt fa-lg"></i>
          <% end %>
          <%= link_to user_todo_list_path(current_user, todo_list), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: "delete" do %>
            <i class="far fa-trash-alt fa-lg"></i>
          <% end %>
        </div>
      </div>
      <div class="todo_items_wrapper">
        <div class="form">
          <%= render "todo_items/form" %>
        </div>
        <div class="items_list">
          <%= render todo_list.todo_items.reverse %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/todo_lists/create.js.erb
$('#blocks .container').last().remove();
$('body #blocks').append("<%= j render @todo_list %>");
$('#blocks .new_list').show().detach().appendTo('#blocks');
$('.footer').remove();
$('#list_<%= @todo_list[:id] %> .items_list').hide();

app/views/todo_lists/destroy.js.erb
$('.delete').bind('ajax:success', function() {
	$(this).closest('.container').fadeOut();
});

app/views/todo_lists/edit.js.erb
$('#list_<%= @todo_list[:id] %> .row').hide().parent().append("<%= j render 'edit' %>");
$('#list_<%= @todo_list[:id] %> .todo_items_wrapper').hide().parent();
$('#list_<%= @todo_list[:id] %> .todo_list_title').first().hide().parent();
$('#list_<%= @todo_list[:id] %>')[0].scrollIntoView({
  behavior: 'auto',
  block: 'center',
  inline: 'center'
});

app/views/todo_lists/index.html.erb
<%= render @todo_lists %>
<div class="new_list">
  <%= link_to new_user_todo_list_path(current_user), remote: true, class: "btn btn-primary btn-lg" do %>
    <i class="fa fa-plus fa-lg"></i>
    <text>Add TODO List</text>
  <% end %>
</div>

app/views/todo_lists/new.js.erb
$('#blocks .new_list').hide().parent().append("<%= j render 'new' %>");
$('.container').last()[0].scrollIntoView({
  behavior: 'auto',
  block: 'center',
  inline: 'center'
});

app/views/todo_lists/update.js.erb
$('#list_<%= @todo_list[:id] %>').closest( ".container" ).replaceWith("<%= j render @todo_list %>");